import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from "next/font/google";
import { cn } from "@/lib/utils";
import QueryProvider from "@/providers/query-provider";

const outfit = Outfit({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={cn(
        "h-full",
        "antialiased",
        GeistSans.variable,
        GeistMono.variable,
        "font-sans",
        outfit.variable
      )}
      lang="en"
    >
      <body className="flex min-h-full flex-col" suppressHydrationWarning>
        <QueryProvider>
          <div className="relative flex min-h-screen flex-col selection:bg-black selection:text-white">
            {children}
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
